package ui;

import models.User;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.time.Day;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

// Most code generated by ChatGPT, and reformatted/tweaked by Brooks

public class HomePage extends JPanel {

    //Home page will be built around the individual user
    private User user;
    private iScreenManager screenManager;
    private DefaultTableModel tableModel;

    //Set up a blank HomePage before user is authenticated (in LoginPage)
    public HomePage(iScreenManager screenManager) {
        this.screenManager = screenManager;
    }
    //
    // Set up HomePage with correct data after user is authenticated (in LoginPage)
    public void setup(User user) {
        this.user = user;

        removeAll(); //removes all components (buttons, panels, charts etc) used to fix TickerPanel
        revalidate(); //forced recalculation of UI
        repaint();

        setLayout(new BorderLayout());
        TickerPanel tickerPanel = new TickerPanel();
        add(tickerPanel, BorderLayout.NORTH);
        add(createChartPanel(user), BorderLayout.CENTER);
        add(createRightPanel(), BorderLayout.EAST);

        System.out.println(user.getUsername() + " " +  user.getPassword());
    }

    private JPanel createChartPanel(User user) {
        JPanel leftPanel = new JPanel(new BorderLayout());

        // === 1. User Info Box (Top of chart panel) ===
        JPanel userInfoPanel = new JPanel();
        userInfoPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 20, 10));
        userInfoPanel.setBackground(new Color(245, 245, 245));
        userInfoPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        JLabel nameLabel = new JLabel("Welcome, " + user.getName());
        nameLabel.setFont(new Font("SansSerif", Font.BOLD, 20));
        nameLabel.setForeground(Color.WHITE);

        JLabel investmentLabel = new JLabel("Total Invested: $" + user.getBalance());
        investmentLabel.setFont(new Font("SansSerif", Font.PLAIN, 16));
        investmentLabel.setForeground(Color.WHITE);

        userInfoPanel.add(nameLabel);
        userInfoPanel.add(Box.createHorizontalStrut(30)); // space between labels
        userInfoPanel.add(investmentLabel);

        userInfoPanel.setBackground(new Color(20, 30, 70));

        leftPanel.add(userInfoPanel, BorderLayout.NORTH);

        // === 2. Chart ===
        JFreeChart chart = createDummyChart();
        ChartPanel chartComponent = new ChartPanel(chart);
        leftPanel.add(chartComponent, BorderLayout.CENTER);

        // === 3. Time Buttons + Logout ===
        JPanel buttonPanel = new JPanel(new BorderLayout());
        buttonPanel.setPreferredSize(new Dimension(0, 50));
        buttonPanel.setBackground(new Color(20, 30, 70));
        buttonPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        JButton logoutButton = new JButton("Logout");
        logoutButton.setBackground(Color.RED);
        logoutButton.setForeground(Color.BLACK);
        buttonPanel.add(logoutButton, BorderLayout.WEST);

        logoutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                User.logOutInstance();
                ((MainFrame) screenManager).loginPage.returnLogin();
                screenManager.switchTo("Login Page");
            }
        });

        JPanel timeButtons = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 0));
        timeButtons.setBackground(new Color(20, 30, 70));

        String[] ranges = {"1D", "1W", "1M", "1Y", "Max"};
        for (String label : ranges) {
            JButton button = new JButton(label);
            button.setBackground(new Color(255, 140, 0));
            button.setForeground(Color.BLACK);
            timeButtons.add(button);
        }

        buttonPanel.add(timeButtons, BorderLayout.CENTER);
        leftPanel.add(buttonPanel, BorderLayout.SOUTH);

        return leftPanel;
    }

    private JPanel createRightPanel() {
        JPanel rightPanel = new JPanel(new BorderLayout());
        rightPanel.setPreferredSize(new Dimension(350, 0));
        rightPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        // Table Column Names
        String[] columnNames = {"NAME", "TYPE", "HOLDING", "PRICE", "GAIN"};
        Object[][] data = {};
        tableModel = new DefaultTableModel(data, columnNames);
        JTable stockTable = new JTable(tableModel);
        stockTable.setRowHeight(30);

        // Table Column Preferences
        stockTable.getColumnModel().getColumn(0).setPreferredWidth(80);
        stockTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        stockTable.getColumnModel().getColumn(2).setPreferredWidth(60);
        stockTable.getColumnModel().getColumn(3).setPreferredWidth(60);

        JScrollPane scrollPane = new JScrollPane(stockTable);
        rightPanel.add(scrollPane, BorderLayout.CENTER);

        // Dummy data
        tableModel.addRow(new Object[]{"AAPL", "Stock", 10, 145.23, 3.5});
        tableModel.addRow(new Object[]{"TSA", "Crypto", 10, 135.23, 3.5});
        tableModel.addRow(new Object[]{"AMZN", "Bond", 101, 142.23, 3.5});
        tableModel.addRow(new Object[]{"NVDA", "Cash", 10, 145.23, 90.5});

        // Buttons
        JPanel userButtonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        userButtonPanel.setPreferredSize(new Dimension(0, 50));
        userButtonPanel.setBackground(new Color(20, 30, 70));
        userButtonPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        JButton addButton = new JButton("Add Stock");
        JButton removeButton = new JButton("Remove Stock");
        JButton resultsButton = new JButton("Risk Profile");

        addButton.addActionListener(e -> {
            screenManager.switchTo("Add Investment");
        });

        resultsButton.addActionListener(e -> {
            screenManager.switchTo("Results Page");
        });

        addButton.setBackground(new Color(255, 140, 0));
        addButton.setForeground(Color.BLACK);
        removeButton.setBackground(new Color(255, 140, 0));
        removeButton.setForeground(Color.BLACK);
        resultsButton.setBackground(new Color(144, 238, 144));
        removeButton.setForeground(Color.BLACK);

        userButtonPanel.add(addButton);
        userButtonPanel.add(removeButton);
        userButtonPanel.add(resultsButton);

        rightPanel.add(userButtonPanel, BorderLayout.SOUTH);

        return rightPanel;
    }

    private JFreeChart createDummyChart() {
        TimeSeries series = new TimeSeries("Investment Portfolio");
        series.add(new Day(1, 4, 2025), 100);
        series.add(new Day(2, 4, 2025), 102);
        series.add(new Day(3, 4, 2025), 105);
        series.add(new Day(4, 4, 2025), 103);
        series.add(new Day(5, 4, 2025), 110);
        series.add(new Day(6, 4, 2025), 112);
        series.add(new Day(7, 4, 2025), 114);
        TimeSeriesCollection dataset = new TimeSeriesCollection();
        dataset.addSeries(series);
        return ChartFactory.createTimeSeriesChart("User Portfolio", "Date", "Price", dataset, false, false, false);
    }
}
